export const RESOURCES = {
  grain: {
    id: 'grain',
    name: 'Sungrain',
    short: 'GRN',
    icon: 'grain',
    tone: '#e9bb67',
    basePrice: 24,
    unit: 'crates',
    blurb: 'Drought-proof seed pressed into travel cakes.',
  },
  alloy: {
    id: 'alloy',
    name: 'Null Alloy',
    short: 'ALL',
    icon: 'alloy',
    tone: '#7fb8d7',
    basePrice: 42,
    unit: 'ingots',
    blurb: 'Memory-metal that keeps a hull from becoming a coffin.',
  },
  relic: {
    id: 'relic',
    name: 'Oldworld Relic',
    short: 'REL',
    icon: 'relic',
    tone: '#c48ce8',
    basePrice: 68,
    unit: 'cases',
    blurb: 'Pre-Collapse curios with a buyer in every port.',
  },
  lumen: {
    id: 'lumen',
    name: 'Lumen Oil',
    short: 'LUM',
    icon: 'lumen',
    tone: '#ee8d70',
    basePrice: 35,
    unit: 'ampoules',
    blurb: 'A volatile light source for the dark side of the sky.',
  },
}

export const FACTIONS = {
  commons: {
    id: 'commons',
    name: 'The Free Commons',
    short: 'COM',
    mark: '✦',
    color: '#8bd4bd',
    description: 'Independent ports held together by mutual risk.',
  },
  verdant: {
    id: 'verdant',
    name: 'Verdant Compact',
    short: 'VDC',
    mark: '◒',
    color: '#b8d978',
    description: 'Seed-keepers who tax every mouth and bless every harvest.',
  },
  iron: {
    id: 'iron',
    name: 'Iron Choir',
    short: 'IRC',
    mark: '◇',
    color: '#90b5d6',
    description: 'A guild of shipwrights, riveters, and patient debt collectors.',
  },
  dusk: {
    id: 'dusk',
    name: 'Dusk Exchange',
    short: 'DSK',
    mark: '◌',
    color: '#d59be7',
    description: 'A polite cartel for dangerous goods and useful secrets.',
  },
}

export const NODES = {
  asterfall: {
    id: 'asterfall',
    name: 'Asterfall',
    code: 'AST-01',
    x: 14,
    y: 51,
    factionId: 'commons',
    color: '#8bd4bd',
    hidden: false,
    hazard: 1,
    weather: 'Crosswinds',
    blurb: 'A battered exchange built into the ribs of a dead sky-whale.',
    specialty: 'Open market',
    market: { grain: 1.06, alloy: 1.08, relic: 0.92, lumen: 1.12 },
    scanText: 'The old whale-bone antenna is still listening. Someone answers from beyond the chart.',
  },
  caligo: {
    id: 'caligo',
    name: 'Caligo Spire',
    code: 'CAL-07',
    x: 35,
    y: 23,
    factionId: 'dusk',
    color: '#d59be7',
    hidden: false,
    hazard: 2,
    weather: 'Glass rain',
    blurb: 'A vertical bazaar where every lift has a different password.',
    specialty: 'Relics & intelligence',
    market: { grain: 1.29, alloy: 0.88, relic: 0.62, lumen: 1.34 },
    scanText: 'A shuttered vault has been warm for three days. The Dusk Exchange calls it a clerical error.',
  },
  veyra: {
    id: 'veyra',
    name: 'Veyra Orchard',
    code: 'VEY-03',
    x: 40,
    y: 75,
    factionId: 'verdant',
    color: '#b8d978',
    hidden: false,
    hazard: 1,
    weather: 'Pollen drift',
    blurb: 'A green shelf above the cloudline, rich in seed and short on metal.',
    specialty: 'Food & medicine',
    market: { grain: 0.62, alloy: 1.26, relic: 1.12, lumen: 0.91 },
    scanText: 'The orchard roots have found a second atmosphere below the shelf. The Compact wants it kept quiet.',
  },
  nacre: {
    id: 'nacre',
    name: 'Nacre Station',
    code: 'NCR-12',
    x: 58,
    y: 45,
    factionId: 'dusk',
    color: '#d59be7',
    hidden: true,
    hazard: 3,
    weather: 'Static bloom',
    blurb: 'A relay station that appears on no official map and every unofficial one.',
    specialty: 'Black-market cargo',
    market: { grain: 1.08, alloy: 1.05, relic: 0.54, lumen: 1.48 },
    scanText: 'Nacre is not a station. It is a paused evacuation fleet, waiting for a signal no one remembers sending.',
  },
  forgehome: {
    id: 'forgehome',
    name: 'Forgehome',
    code: 'FOR-22',
    x: 75,
    y: 70,
    factionId: 'iron',
    color: '#90b5d6',
    hidden: true,
    hazard: 2,
    weather: 'Magnet squall',
    blurb: 'A shipyard-city welded around a perpetual furnace.',
    specialty: 'Hullworks & alloy',
    market: { grain: 1.21, alloy: 0.57, relic: 1.18, lumen: 1.06 },
    scanText: 'The Choir is building something beneath the furnace. It has a keel, but no name.',
  },
  moonwake: {
    id: 'moonwake',
    name: 'Moonwake Array',
    code: 'MWK-31',
    x: 80,
    y: 22,
    factionId: 'commons',
    color: '#8bd4bd',
    hidden: true,
    hazard: 4,
    weather: 'Long night',
    blurb: 'A listening post suspended above the moon’s permanent shadow.',
    specialty: 'Lumen & navigation',
    market: { grain: 0.9, alloy: 1.16, relic: 0.75, lumen: 0.72 },
    scanText: 'A navigation pulse repeats every thirteen minutes. It is not a beacon. It is a countdown.',
  },
}

export const ROUTES = [
  ['asterfall', 'caligo'],
  ['asterfall', 'veyra'],
  ['asterfall', 'nacre'],
  ['caligo', 'nacre'],
  ['caligo', 'moonwake'],
  ['nacre', 'forgehome'],
  ['nacre', 'moonwake'],
  ['veyra', 'forgehome'],
  ['forgehome', 'moonwake'],
]

export const CREW = [
  {
    id: 'mara',
    name: 'Mara Venn',
    role: 'Wayfinder',
    specialty: 'Command',
    cost: 0,
    icon: 'compass',
    color: '#8bd4bd',
    description: 'Knows the difference between a shortcut and an ending.',
    effect: 'Keeps the ship moving.',
  },
  {
    id: 'sable',
    name: 'Sable Quill',
    role: 'Broker',
    specialty: 'Markets',
    cost: 180,
    icon: 'ledger',
    color: '#e9bb67',
    description: 'Can smell a desperate buyer through three sealed bulkheads.',
    effect: 'Improves sale prices by 6%.',
  },
  {
    id: 'oren',
    name: 'Oren Pike',
    role: 'Rigger',
    specialty: 'Navigation',
    cost: 210,
    icon: 'route',
    color: '#7fb8d7',
    description: 'Ties knots that hold when the sky forgets which way is down.',
    effect: 'Reduces travel fuel by 1.',
  },
  {
    id: 'vesper',
    name: 'Vesper Nix',
    role: 'Listener',
    specialty: 'Signals',
    cost: 240,
    icon: 'signal',
    color: '#c48ce8',
    description: 'Answers questions before you decide whether to ask them.',
    effect: 'Surveys reveal an extra Insight.',
  },
]

export const UPGRADES = [
  {
    id: 'keel',
    name: 'Reinforced Keel',
    cost: 160,
    icon: 'shield',
    color: '#7fb8d7',
    description: 'Layered null-alloy ribs turn bad routes into manageable stories.',
    effect: '+20 maximum hull integrity.',
  },
  {
    id: 'lattice',
    name: 'Cargo Lattice',
    cost: 220,
    icon: 'box',
    color: '#e9bb67',
    description: 'Fold-space braces let the hold carry awkward, valuable shapes.',
    effect: '+5 cargo capacity.',
  },
  {
    id: 'array',
    name: 'Longglass Array',
    cost: 260,
    icon: 'signal',
    color: '#c48ce8',
    description: 'A tuned receiver turns distant noise into actionable routes.',
    effect: 'Surveying costs no Insight and reveals safer route data.',
  },
]

export const WEATHER = [
  {
    name: 'Clear Meridian',
    code: 'CLR',
    tone: '#8bd4bd',
    description: 'Trade lanes settle. Travel is predictable.',
    effect: 'Travel hazards -1.',
  },
  {
    name: 'Glass Rain',
    code: 'GLS',
    tone: '#d59be7',
    description: 'Shards of old satellites make every route a wager.',
    effect: 'Relics sell for +10%; travel hazards +1.',
  },
  {
    name: 'Pollen Drift',
    code: 'POL',
    tone: '#b8d978',
    description: 'A sweet cloud moves between the shelves, carrying rumors.',
    effect: 'Sungrain buys for -10%; Survey reveals +1 Insight.',
  },
  {
    name: 'Magnet Squall',
    code: 'MAG',
    tone: '#7fb8d7',
    description: 'Compasses lie. Metal sings. The Choir gets busy.',
    effect: 'Alloy sells for +12%; hull damage +1.',
  },
  {
    name: 'Long Night',
    code: 'NGT',
    tone: '#ee8d70',
    description: 'The sun drops below the world and lumen becomes king.',
    effect: 'Lumen sells for +15%; every watch restores less fuel.',
  },
]

export const CONTRACT_BLUEPRINTS = [
  {
    id: 'root-and-rivet',
    title: 'Root & Rivet',
    factionId: 'verdant',
    cargo: 'alloy',
    amount: 3,
    destination: 'veyra',
    reward: 210,
    renown: 3,
    expires: 8,
    brief: 'The orchard’s irrigation spine is splitting. Forge-grade alloy, before the next bloom.',
  },
  {
    id: 'quiet-lights',
    title: 'Quiet Lights',
    factionId: 'commons',
    cargo: 'lumen',
    amount: 4,
    destination: 'asterfall',
    reward: 245,
    renown: 3,
    expires: 7,
    brief: 'Asterfall needs a week of light without announcing why. Do not ask the dockmaster.',
  },
  {
    id: 'museum-of-ashes',
    title: 'Museum of Ashes',
    factionId: 'dusk',
    cargo: 'relic',
    amount: 2,
    destination: 'caligo',
    reward: 260,
    renown: 4,
    expires: 9,
    brief: 'A collector wants two pre-Collapse objects. Provenance is optional; discretion is not.',
  },
  {
    id: 'the-long-haul',
    title: 'The Long Haul',
    factionId: 'iron',
    cargo: 'grain',
    amount: 6,
    destination: 'forgehome',
    reward: 340,
    renown: 5,
    expires: 12,
    brief: 'The furnace crews have forgotten what a meal is. Bring grain, not promises.',
  },
  {
    id: 'signal-in-the-dark',
    title: 'Signal in the Dark',
    factionId: 'commons',
    cargo: 'relic',
    amount: 1,
    destination: 'moonwake',
    reward: 430,
    renown: 6,
    expires: 14,
    brief: 'Carry one silent relic to Moonwake. If it begins to hum, turn around.',
  },
]

export const TAB_META = {
  chart: { label: 'Chart', eyebrow: 'LIVE ROUTES', title: 'The Meridian', icon: 'map' },
  market: { label: 'Market', eyebrow: 'OPEN EXCHANGE', title: 'Price Currents', icon: 'trend' },
  contracts: { label: 'Contracts', eyebrow: 'ACTIVE WORK', title: 'The Noticeboard', icon: 'contract' },
  ship: { label: 'Ship & Crew', eyebrow: 'THE VESSEL', title: 'Wayfarer / 09', icon: 'ship' },
  codex: { label: 'Codex', eyebrow: 'FIELD NOTES', title: 'The Living Ledger', icon: 'book' },
}

export const INITIAL_LOG = [
  { id: 'log-0', kind: 'system', title: 'The Wayfarer is awake', detail: 'Asterfall exchange has granted you a provisional route license.', day: 1, time: '06:10' },
  { id: 'log-1', kind: 'intel', title: 'Rumor intercepted', detail: 'Veyra Orchard is paying above rate for Null Alloy. Someone is repairing something large.', day: 1, time: '06:24' },
]
